var Constants = {
    $_DIR: {
        Payline:"/Content/img/paylines/"
    },
    
    $_PLAY_BUTTON: "playButton",
    $_SPACE_PRESS: "spacePress",
    $_GAME_READY: "gameReady", 
    $_GAME_INITED: "gameInited",
    $_DISPLAY_GAME: "displayGame",
    $_START_ANIMATION: "startAnimation",
    $_START_WIN_ANIMATION: "startWinAnimation",
    $_SERVER_RESPONSE: "serverResponse",
    $_GAME_ENGINE_NOTIFICATION: "gameEngineNotification",
    $_SLOT_ENGINE_NOTIFICATION: "slotEngineNotification",
    $_REEL_CONTROLLER_NOTIFICATION: 'reelControllerNotification',
    $_ANIMATION_CONTROLLER_NOTIFICATION: 'animControllerNotification',
    $_GAMBLER_NOTIFICATION: "gamblerNotification",
    $_GAMBLE_RESULT_RECIEVED: "gambleResultRecieved",
    $_UPDATE_REELS: "updateReels",
    $_CLIENT_PLACE_BET: "placeBet",
    $_SPIN_REELS: "spinReels",
    $_STOP_REELS: "stopReels",
    $_LOAD_SPRITE: "loadSprite",
    $_SERVER_REQUEST: "serverRequest",
    $_SERVER_GAMBLE_REQUEST: "serverGambleRequest",
    $_SERVER_CONNECTED: "serverConnected",
    $_SERVER_BET_START: "serverBetStart",
    $_SERVER_BET_RESULT: "serverBetResult",
    $_SERVER_BET_RESULT_WIN: "serverBetResultWin",
    $_REEL_COMMAND: "reelCommand",
    $_REEL_STOPPED: "reelStopped",
    $_REEL_ANIMATIONS_COMPLETE: "animationComplete",
    $_PAYLINE_ANIMATION_COMPLETE: "paylineAnimationsComplete",
    $_ALL_ANIMATIONS_COMPLETE: "allAnimationsComplete",
    $_FINAL_IMG_READY: "finalImageReady",
    $_ALL_REELS_FROZEN: "onAllReelsFrozen",
    $_AUTOPLAY: "autoplay",
    $_START_AUTOPLAY: "startAutoplay",
    $_STOP_AUTOPLAY: "startAutoplay",
    $_SHOW_GAMBLE: "showGamble",
    $_CLOSE_GAMBLE: "closeGamble",
    $_NONE: "none"
}
